//
//  Search_OpportunityList_Var.m
//  DSM
//
//  Created by Sachin Sharma on 24/04/15.
//  Copyright (c) 2015 LetsIDev. All rights reserved.
//
#import "Search_OpportunityList_Var.h"

Search_OpportunityList_Var *searchOppListVar;
NSMutableArray *SearchOpportunityListArray;
NSMutableArray *DisplaySearchOpportunityDetailsArray;

@implementation Search_OpportunityList_Var


@synthesize OPTY_ID,OPTY_NAME,OPTY_CREAT_DATE,PRODUCT_NAME,PRODUCT_NAME1,VC,TGM_TKM_NAME,TGM_TKM_PHONE_NUMBER,ACCOUNT_ID,ACCOUNT_TYPE,SALE_STAGE_NAME,SALES_STAGE_DATE,LEAD_ASSIGNED_NAME,LEAD_ASSIGNED_POSITION,LEAD_ASSIGNED_CELL_NUMBER,LEAD_ASSIGNED_POSITION_ID,CONTACT_NAME,CONTACT_FIRST_NAME,CONTACT_LAST_NAME,CONTACT_ID,CONTACT_ADDRESS,CONTACT_CELL_NUMBER,ADDRESS_ID,LAST_PENDING_ACTIVITY_TYPE,LAST_DONE_ACTIVITY_ID,LAST_PENDING_ACTIVITY_STATUS,LAST_PEND_ACTIVIY_START_DATE,LAST_PENDING_ACTIVITY_DESC,LAST_PENDING_ACTIVITY_ID,LAST_DONE_ACTIVITY_DATE,LAST_DONE_ACTIVITY_DESC,LAST_DONE_ACTIVITY_TYPE,X_TALUKA,CUSTOMER_ACCOUNT_NAME,CUSTOMER_ACCOUNT_ID,REV_PRODUCT_ID,PRODUCT_ID,ACCOUNT_PHONE_NUMBER,ACCOUNT_NAME,
ACCOUNT_LOCATION,
RNUM,
RESULT_COUNT,
MAKE_LOST_TO,
MODEL_LOST_TO,
CLOSURE_SUMMARY,
REASON_LOST,PARENT_PROD_LINE,PRODUCT_LINE,OPTY_CREATED_DATE,LEAD_POSITION,
CUSTOMER_ACCOUNT_LOCATION,
CUSTOMER_PHONE_NUMBER,
PPL;

@end
