//
//  Activity_List.m
//  CRM_APP
//
//  Created by Nihal Shaikh on 10/19/15.
//  Copyright (c) 2015 TataTechnologies. All rights reserved.
//

#import "Activity_List.h"


Activity_List *activity_list,*activityDashobard;
NSMutableArray *Activities_ListArr,*Activities_Customer_list,*Activities_ListDashBoardArr,*Activities_ListDashBoard30DaysArr;
NSMutableArray *Activities_ListDisplayArr;

@implementation Activity_List

@synthesize X_PROSPECT_SRC,ACTIVITY_ROW_ID,ACTIVITY_TYPE,ACTIVITY_PLAN_START_DATE,ACTIVITY_CREATED_DATE,ACTIVITY_COMPLETION_DATE,ACTIVITY_STATUS,
DESCRIPTION,OPTY_CREAT_DATE,OPPTY_ROWID,OPPTY_NAME,PRODUCT_NAME1,PRODUCT_LINE,VC,CONTACT_ID,CONTACT_NAME,CONTACT_CELL_NUM,
CONTACT_ADDRESS,ADDRESS_ID,ACCOUNT_ID,ACCOUNT_NAME,ACCOUNT_PHONE_NUMBER,ACCOUNT_LOCATION,SALES_STAGE_DATE,SALES_STAGE_NAME,RNUM,RESULT_COUNT,LEAD_ASSIGNED_CELL_NUMBER,LEAD_ASSIGNED_NAME,LEAD_ASSIGNED_POSITION_ID,LEAD_ASSIGNED_POSITION_NAME,ACTIVITY_PENDING_TYPE,PARENT_PRODUCT_NAME,OPTY_ID,OPTY_CREATED,POSTN_TYPE_CD,ACTIVITY_ID,PLANNED_START_DATE,ACTIVITY_DESCRIPTION,X_TALUKA,TGM_TKM_NAME,TGM_TKM_PHONE_NUMBER;



@end
