//
//  Opportunity_List.m
//  sfa
//
//  Created by Admin on 27/02/14.
//  Copyright (c) 2014 ttl. All rights reserved.
//

#import "Opportunity_List.h"

Opportunity_List *opportunity_list,*searchOpportunity_list;
NSMutableArray *OpportunityListArr;
NSMutableArray *OpportunityListDisplayArr;
NSMutableArray *OpportunityList_ArrList;
NSMutableArray *searchoptycontactarray;

@implementation Opportunity_List

@synthesize OPTY_ID,OPTY_NAME,OPTY_CREAT_DATE,PRODUCT_NAME,PRODUCT_NAME1,VC,TGM_TKM_NAME,TGM_TKM_PHONE_NUMBER,ACCOUNT_ID,ACCOUNT_TYPE,SALE_STAGE_NAME,SALES_STAGE_DATE,LEAD_ASSIGNED_NAME,LEAD_ASSIGNED_POSITION,LEAD_ASSIGNED_CELL_NUMBER,LEAD_ASSIGNED_POSITION_ID,CONTACT_NAME,CONTACT_FIRST_NAME,CONTACT_LAST_NAME,CONTACT_ID,CONTACT_ADDRESS,CONTACT_CELL_NUMBER,ADDRESS_ID,LAST_PENDING_ACTIVITY_TYPE,LAST_DONE_ACTIVITY_ID,LAST_PENDING_ACTIVITY_STATUS,LAST_PEND_ACTIVIY_START_DATE,LAST_PENDING_ACTIVITY_DESC,LAST_PENDING_ACTIVITY_ID,LAST_DONE_ACTIVITY_DATE,LAST_DONE_ACTIVITY_DESC,LAST_DONE_ACTIVITY_TYPE,X_TALUKA,CUSTOMER_ACCOUNT_NAME,CUSTOMER_ACCOUNT_ID,REV_PRODUCT_ID,PRODUCT_ID,RESULT_COUNT,RNUM,ACCOUNT_NAME,CUSTOMER_ACCOUNT_LOCATION,CUSTOMER_PHONE_NUMBER,OPTY_CREATED_DATE,CUSTOMER_ACCOUNT_MOBNUMBER,FIN_NAME,Campaign_NAME,Campaign_ID,FIN_ID;;

@end
